"""SCHEMA: Increase length of file_type column in uploaded_file table

Revision ID: 87e204e34efc
Revises: 244032c11919
Create Date: 2025-05-17 09:56:22.394095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e204e34efc'
down_revision = '244032c11919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_file', schema=None) as batch_op:
        batch_op.alter_column('file_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_file', schema=None) as batch_op:
        batch_op.alter_column('file_type',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
