"""Add processed_file_path to CVEntry

Revision ID: 9e6006a9a408
Revises: 
Create Date: 2025-05-14 15:25:18.777177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e6006a9a408'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processed_file_path', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv_entry', schema=None) as batch_op:
        batch_op.drop_column('processed_file_path')

    # ### end Alembic commands ###
